---
- name: Create ServiceNow Credential Type
  awx.awx.credential_type:
    name: "{{ credential_type.name }}"
    description: "{{ credential_type.description }}"
    kind: "{{ credential_type.kind }}"
    inputs: "{{ credential_type.inputs }}"
    injectors: "{{ credential_type.injectors }}"
    state: present

 
- name: Add ServiceNow Credentials
  awx.awx.tower_credential:
    name: ServiceNow Credentials
    description: "Credentials for ServiceNow environment"
    credential_type: ServiceNow
    organization: "{{ organization }}"
    inputs:
      SNOW_INSTANCE: "dev6666"
      SNOW_PASSWORD: "PASSOWRD"
      SNOW_USERNAME: "user"
    